apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      securityContext:
        runAsUser: 200
        fsGroup: 200
      containers:
        - name: nexus3
          image: raonadeem/nexus3:v1
          ports:
          - containerPort: 8081
          volumeMounts:
          - mountPath: "/nexus-data"
            name: nexus-data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
